// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncbgltztigxkfxqvwlcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jYmdsdHp0aWd4a2Z4cXZ3bGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDc1NTIsImV4cCI6MjA3NDIyMzU1Mn0.ImS9ZWIcnKGdNNsS9fFnaNdygPTCn9r1UlzJFP3WFIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});